version: '3.9'
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      default:
        ipv4_address: 10.1.0.19
networks:
  default:
    external:
      name: krak_island
volumes:
  portainer_data:
    external: true
